version: "3"
services:
  web_beginingrails6:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "3009:3000"
    volumes: 
      - ./beginingrails6:/opt/app
      - gem_cache_beginingrails6:/gems
    env_file: 
      - .env/development/database_beginingrails6
      - .env/development/web_beginingrails6
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server_beginingrails6
    networks:
      - network
  webpack_dev_server_beginingrails6:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/webpack-dev-server
    ports: 
      - "3044:3044"
    volumes: 
      - ./beginingrails6:/opt/app
      - gem_cache_beginingrails6:/gems
    env_file: 
      - .env/development/database_beginingrails6
      - .env/development/web_beginingrails6
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    networks:
      - network
  database_beginingrails6:
    image: postgres
    env_file: 
      - .env/development/database_beginingrails6
    volumes: 
      - db_data_beginingrails6:/var/lib/postgresql/data
    networks:
      - network
volumes: 
  db_data_beginingrails6:
  gem_cache_beginingrails6:
networks:
  network: